In [182]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import rand_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import warnings
from numpy.random import randn
warnings.filterwarnings('ignore')
import sklearn.neighbors
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from keras.models import Sequential
from sklearn import metrics
from tensorflow import keras
from keras.layers import Dense, Input
from keras.models import Model
from keras.optimizers import Adam

In [183]:


df = pd.read_csv(r'C:\Users\parab\HeartData2\HispanicData.csv')
df=df.drop(columns=['Unnamed: 0'])
df

HeartDisease    BMI  Smoking  AlcoholDrinking  Stroke  PhysicalHealth   
0                0  25.83        0                0       0             0.0  \
1                0  25.85        0                0       0             0.0   
2                0  38.09        0                0       0             4.0   
3                0  27.89        1                0       0             0.0   
4                0  35.67        1                0       0            30.0   
...            ...    ...      ...              ...     ...             ...   
1995             0  22.45        0                0       0             0.0   
1996             0  28.80        0                0       0             0.0   
1997             0  32.28        0                0       0             0.0   
1998             0  24.39        0                0       0             0.0   
1999             0  20.78        0                0       0             0.0   

      MentalHealth  DiffWalking  Sex  AgeCategory  Diabetic  PhysicalActivity   
0              0.0            0    1           65       0.0                 1  \
1              1.0            0    0           18       0.0                 1   
2             10.0            0    0           55       1.0                 1   
3              0.0            0    1           70       0.0                 1   
4             15.0            1    1           40       1.0                 0   
...            ...          ...  ...          ...       ...               ...   
1995          14.0            0    0           45       0.0                 1   
1996           0.0            0    1           50       0.0                 1   
1997           0.0            0    1           18       0.0                 0   
1998           0.0            0    1           45       0.0                 1   
1999           0.0            0    0           35       0.0                 1   

      GenHealth  SleepTime  Asthma  KidneyDisease  SkinCancer  
0             4        9.0       0              0           0  
1             5        6.0       0              0           0  
2             2        8.0       0              1           0  
3             3        7.0       0              0           1  
4             2        7.0       1              0           0  
...         ...        ...     ...            ...         ...  
1995          4        5.0       0              0           1  
1996          5        6.0       0              0           0  
1997          5        8.0       0              0           0  
1998          5        6.0       1              0           0  
1999          4        9.0       0              0           0  

[2000 rows x 17 columns]

In [184]:
x = df.iloc[:, 1:]
y = df.iloc[:, 0]
y

0       0
1       0
2       0
3       0
4       0
       ..
1995    0
1996    0
1997    0
1998    0
1999    0
Name: HeartDisease, Length: 2000, dtype: int64

In [185]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 0, test_size = 0.35)

In [186]:
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [187]:
print(x_test)

[[-0.74895782 -0.66666667 -0.24568046 ... -0.37995552 -0.17115878
  -0.14002801]
 [ 0.47375181 -0.66666667 -0.24568046 ...  2.63188702 -0.17115878
  -0.14002801]
 [-0.62519575 -0.66666667 -0.24568046 ... -0.37995552 -0.17115878
  -0.14002801]
 ...
 [ 0.49760955 -0.66666667 -0.24568046 ...  2.63188702 -0.17115878
  -0.14002801]
 [ 0.70934707 -0.66666667 -0.24568046 ...  2.63188702 -0.17115878
  -0.14002801]
 [ 0.85249357  1.5        -0.24568046 ... -0.37995552 -0.17115878
  -0.14002801]]


In [188]:
import math
math.sqrt(len(y_test))

26.457513110645905

In [189]:
classifier = KNeighborsClassifier(n_neighbors = 26, p = 2, metric = 'euclidean')
classifier.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=26)

In [190]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [191]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[666   0]
 [ 34   0]]


In [192]:
print(accuracy_score(y_test,y_pred))
print(f1_score(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(recall_score(y_test,y_pred))
print(rand_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.9514285714285714
0.0
0.0
0.0
0.9074432863274065
0.04857142857142857


In [193]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)

In [194]:
y_pred = clf.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [195]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[665   1]
 [ 32   2]]


In [196]:
print(accuracy_score(y_test,y_pred))
print(f1_score(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(recall_score(y_test,y_pred))
print(rand_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.9528571428571428
0.10810810810810811
0.6666666666666666
0.058823529411764705
0.9100306560392397
0.047142857142857146


In [197]:
rf = RandomForestClassifier(n_estimators=500, random_state=12, max_depth=5)
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)

In [198]:
rf_conf_matrix = confusion_matrix(y_test, y_pred)
print("confusion matrix")
print(rf_conf_matrix)

confusion matrix
[[666   0]
 [ 34   0]]


In [199]:
print(accuracy_score(y_test,y_pred))
print(f1_score(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(recall_score(y_test,y_pred))
print(rand_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))


0.9514285714285714
0.0
0.0
0.0
0.9074432863274065
0.04857142857142857
