In [91]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import rand_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import warnings
from numpy.random import randn
warnings.filterwarnings('ignore')
import sklearn.neighbors
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from keras.models import Sequential
from sklearn import metrics
from tensorflow import keras
from keras.layers import Dense, Input
from keras.models import Model
from keras.optimizers import Adam

In [92]:


df = pd.read_csv(r'C:\Users\parab\HeartData2\HispanicData.csv')
df1 = pd.read_csv(r'C:\Users\parab\HeartData2\fakehispanicdata.data')
df=df.drop(columns=['Unnamed: 0'])
df1=df1.drop(columns=['Unnamed: 0'])
df1

HeartDisease        BMI  Smoking  AlcoholDrinking  Stroke   
0               0  12.844709        0                0       1  \
1               0  11.454284        0                1       0   
2               0  10.546164        0                0       0   
3               0  28.053598        0                0       0   
4               0  31.272509        0                1       0   
..            ...        ...      ...              ...     ...   
695             1  49.100450        1                1       0   
696             0  13.820496        0                0       1   
697             0  13.251126        0                0       0   
698             0  50.770313        0                0       0   
699             0  22.879600        0                0       0   

     PhysicalHealth  MentalHealth  DiffWalking  Sex  AgeCategory  Diabetic   
0          1.562890     -0.386295            0    0    11.025727         0  \
1          0.478604     -0.802054            0    0    28.673817         0   
2          1.170921      0.908862            0    0    20.143380         0   
3         -0.766646      2.551180            0    1    21.240183         0   
4          0.478454      0.152980            0    1    60.428337         0   
..              ...           ...          ...  ...          ...       ...   
695        4.058693     -1.315329            1    1    97.126770         1   
696        1.766544      1.493705            0    0    26.300335         0   
697       -0.271803      0.950670            0    0    11.084663         0   
698        0.240862      3.365431            0    1    71.501274         1   
699       -1.139381      1.923866            0    1    22.539719         0   

     PhysicalActivity  GenHealth  SleepTime  Asthma  KidneyDisease  SkinCancer  
0                   0        2.0   1.928197       1              1           1  
1                   0        3.0   3.301313       1              1           0  
2                   0        2.0   1.983913       1              1           1  
3                   1        3.0   8.776337       1              1           1  
4                   1        3.0   9.528002       1              0           0  
..                ...        ...        ...     ...            ...         ...  
695                 1        4.0   9.971811       0              0           0  
696                 0        2.0   2.311657       1              1           1  
697                 0        3.0   4.134563       1              1           1  
698                 1        5.0  14.775149       1              0           0  
699                 1        3.0   7.712715       1              1           1  

[700 rows x 17 columns]

In [93]:
x = df.iloc[:, 1:]
y = df.iloc[:, 0]
x1 = df1.iloc[:, 1:]
y1 = df1.iloc[:, 0]
y

0       0
1       0
2       0
3       0
4       0
       ..
1995    0
1996    0
1997    0
1998    0
1999    0
Name: HeartDisease, Length: 2000, dtype: int64

In [94]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 0, test_size = 0.35)
print(len(x_train))
x_train=pd.concat([x_train,x1])
y_train=pd.concat([y_train,y1])

1300


In [95]:
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)
print(len(x_train))

2000


In [96]:
print(x_test)

[[-0.45802955 -0.72254413 -0.4209074  ... -0.66011376 -0.55964063
  -0.53649791]
 [ 0.36224013 -0.72254413 -0.4209074  ...  1.5148904  -0.55964063
  -0.53649791]
 [-0.37500225 -0.72254413 -0.4209074  ... -0.66011376 -0.55964063
  -0.53649791]
 ...
 [ 0.3782454  -0.72254413 -0.4209074  ...  1.5148904  -0.55964063
  -0.53649791]
 [ 0.5202921  -0.72254413 -0.4209074  ...  1.5148904  -0.55964063
  -0.53649791]
 [ 0.61632367  1.38399852 -0.4209074  ... -0.66011376 -0.55964063
  -0.53649791]]


In [97]:
import math
math.sqrt(len(y_test))

26.457513110645905

In [98]:
classifier = KNeighborsClassifier(n_neighbors = 26, p = 2, metric = 'euclidean')
classifier.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=26)

In [99]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [100]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[662   4]
 [ 32   2]]


In [101]:
print(accuracy_score(y_test,y_pred))
print(f1_score(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(recall_score(y_test,y_pred))
print(rand_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.9485714285714286
0.1
0.3333333333333333
0.058823529411764705
0.9022930717351318
0.05142857142857143


In [102]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)

In [103]:
y_pred = clf.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [104]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[665   1]
 [ 33   1]]


In [105]:
print(accuracy_score(y_test,y_pred))
print(f1_score(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(recall_score(y_test,y_pred))
print(rand_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.9514285714285714
0.05555555555555555
0.5
0.029411764705882353
0.9074432863274065
0.04857142857142857


In [106]:
rf = RandomForestClassifier(n_estimators=500, random_state=12, max_depth=5)
rf.fit(x_train,y_train)
rf_predicted = rf.predict(x_test)

In [107]:
rf_conf_matrix = confusion_matrix(y_test, rf_predicted)
print("confusion matrix")
print(rf_conf_matrix)

confusion matrix
[[665   1]
 [ 31   3]]


In [108]:
print(accuracy_score(y_test,y_pred))
print(f1_score(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(recall_score(y_test,y_pred))
print(rand_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))


0.9514285714285714
0.05555555555555555
0.5
0.029411764705882353
0.9074432863274065
0.04857142857142857
