In [73]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import rand_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import warnings
from numpy.random import randn
warnings.filterwarnings('ignore')
import sklearn.neighbors
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from keras.models import Sequential
from sklearn import metrics
from tensorflow import keras
from keras.layers import Dense, Input
from keras.models import Model
from keras.optimizers import Adam

In [74]:


df = pd.read_csv(r'C:\Users\parab\HeartData2\HispanicData.csv')
df1 = pd.read_csv(r'C:\Users\parab\HeartData2\fakehispanicdiseasedata.data')
df=df.drop(columns=['Unnamed: 0'])
df1=df1.drop(columns=['Unnamed: 0'])
df1

HeartDisease        BMI  Smoking  AlcoholDrinking  Stroke   
0               1  14.449534        1                0       0  \
1               1  17.387936        1                0       1   
2               1  20.329737        1                0       1   
3               1  10.361368        1                0       1   
4               1  38.347874        0                1       1   
..            ...        ...      ...              ...     ...   
395             1  28.260365        1                0       0   
396             1  22.065039        0                0       1   
397             1  15.066922        1                0       0   
398             1  20.642883        1                1       0   
399             1  31.434887        0                0       0   

     PhysicalHealth  MentalHealth  DiffWalking  Sex  AgeCategory  Diabetic   
0         13.827834     21.757858            1    0    42.603750         1  \
1         11.364265      4.869201            1    0    59.856297         0   
2          6.393329      4.993457            1    0    61.048378         1   
3          4.188243      2.360053            1    0    31.347332         0   
4          1.757519     -1.549731            1    1   105.284350         1   
..              ...           ...          ...  ...          ...       ...   
395        1.252225      4.614945            1    1    33.802437         0   
396        0.702899     -1.085838            1    0    56.996555         1   
397       15.804435     22.162363            1    0    48.882260         1   
398        3.993920     15.523002            1    0    31.478142         1   
399        0.718106     -0.144948            0    1    46.924362         0   

     PhysicalActivity  GenHealth  SleepTime  Asthma  KidneyDisease  SkinCancer  
0                   1        2.0   6.083590       0              1           1  
1                   0        2.0   6.328973       0              1           1  
2                   0        2.0   6.305020       0              1           1  
3                   1        2.0   3.337939       0              0           0  
4                   1        3.0  11.117983       0              1           0  
..                ...        ...        ...     ...            ...         ...  
395                 0        3.0   6.360140       1              0           0  
396                 1        3.0   6.229015       0              0           0  
397                 1        2.0   6.109014       0              1           1  
398                 1        3.0   5.621524       0              0           0  
399                 0        3.0   7.641015       1              0           1  

[400 rows x 17 columns]

In [75]:
x = df.iloc[:, 1:]
y = df.iloc[:, 0]
x1 = df1.iloc[:, 1:]
y1 = df1.iloc[:, 0]
y

0       0
1       0
2       0
3       0
4       0
       ..
1995    0
1996    0
1997    0
1998    0
1999    0
Name: HeartDisease, Length: 2000, dtype: int64

In [76]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 0, test_size = 0.35)
x_train=pd.concat([x_train,x1])
y_train=pd.concat([y_train,y1])
print(len(x_train))

1700


In [77]:
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [78]:
print(x_test)

[[-0.5607011  -0.72433672 -0.41132523 ... -0.51009091 -0.37439869
  -0.35472217]
 [ 0.40796468 -0.72433672 -0.41132523 ...  1.96043486 -0.37439869
  -0.35472217]
 [-0.46265322 -0.72433672 -0.41132523 ... -0.51009091 -0.37439869
  -0.35472217]
 ...
 [ 0.42686548 -0.72433672 -0.41132523 ...  1.96043486 -0.37439869
  -0.35472217]
 [ 0.59461004 -0.72433672 -0.41132523 ...  1.96043486 -0.37439869
  -0.35472217]
 [ 0.70801481  1.3805734  -0.41132523 ... -0.51009091 -0.37439869
  -0.35472217]]


In [79]:
import math
math.sqrt(len(y_test))

26.457513110645905

In [80]:
classifier = KNeighborsClassifier(n_neighbors = 26, p = 2, metric = 'euclidean')
classifier.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=26)

In [81]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [82]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[662   4]
 [ 28   6]]


In [83]:
print(accuracy_score(y_test,y_pred))
print(f1_score(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(recall_score(y_test,y_pred))
print(rand_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.9542857142857143
0.2727272727272727
0.6
0.17647058823529413
0.9126262006948702
0.045714285714285714


In [84]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)

In [85]:
y_pred = clf.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [86]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[655  11]
 [ 24  10]]


In [87]:
print(accuracy_score(y_test,y_pred))
print(f1_score(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(recall_score(y_test,y_pred))
print(rand_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.95
0.3636363636363637
0.47619047619047616
0.29411764705882354
0.9048640915593705
0.05


In [88]:
rf = RandomForestClassifier(n_estimators=500, random_state=12, max_depth=5)
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)

In [89]:
rf_conf_matrix = confusion_matrix(y_test, y_pred)
print("confusion matrix")
print(rf_conf_matrix)

confusion matrix
[[656  10]
 [ 28   6]]


In [90]:
print(accuracy_score(y_test,y_pred))
print(f1_score(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(recall_score(y_test,y_pred))
print(rand_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))


0.9457142857142857
0.24
0.375
0.17647058823529413
0.8971755569180462
0.054285714285714284
